//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTb1
    {
        public int BID { get; set; }
        public string BTitle { get; set; }
        public string BTACGIA { get; set; }
        public string BTHELOAI { get; set; }
        public int BCL { get; set; }
        public int BGIA { get; set; }
    }
}
