//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BOOKSHOPDBEntities : DbContext
    {
        public BOOKSHOPDBEntities()
            : base("name=BOOKSHOPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillTb1> BillTb1 { get; set; }
        public virtual DbSet<BookTb1> BookTb1 { get; set; }
        public virtual DbSet<UserTb1> UserTb1 { get; set; }
    }
}
