//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOKSTORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTb1
    {
        public int UId { get; set; }
        public string Uname { get; set; }
        public string Uphone { get; set; }
        public string UAdd { get; set; }
        public string UPass { get; set; }
    }
}
